/** @type {import('@ianvs/prettier-plugin-sort-imports').PrettierConfig} */
module.exports = {
  endOfLine: "lf",
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  printWidth: 100,
  trailingComma: "es5",
  arrowParens: "avoid",
  importOrder: [
    // "<TYPES>",
    // "<TYPES>^[.]",
    "<BUILTIN_MODULES>",
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<THIRD_PARTY_MODULES>",
    "",
    // "^types$",
    "^@/type[s]?(.*)$",
    "^@/config[s]?(.*)$",
    "^@/provider[s]?(.*)$",
    "^@/lib[s]?(.*)$",
    "^@/action[s]?(.*)$",
    "^@/hook[s]?(.*)?$",
    "",
    "^@/component[s]?/ui(.*)$",
    "^@/component[s]?(.*)$",
    "",
    "^@/style(.*)$",
    "^@/(.*)$",
    "",
    "^[./]",
    "",
    "^(?!.*[.]css$)[./].*$",
    ".css$",
  ],
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  plugins: ["@ianvs/prettier-plugin-sort-imports", "prettier-plugin-tailwindcss"],
}
