import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "./globals.css"

import { ToastHot } from "@/components/ui/toast"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gradient-primary h-full overflow-y-auto">
          {children}
          <ToastHot />
        </div>
      </body>
    </html>
  )
}
